Fix chunk=0 when B > rows (#493)
For me I hit this when setting things really low for testing 
```
        num_generations=2,
        per_device_train_batch_size=1
```

ended up with the error

```
      680 pass                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
      682 all_logprobs_list = []                                                                                                                                                                                                                                                                                                                                                                                                                                                
  --> 684 attention_mask_chunks = torch.chunk(attention_mask, chunks=B, dim=0)                                                                                                                                                                                                                                                                                                                                                                                                  
      685 completion_ids_chunks = torch.chunk(completion_input_ids, chunks=B, dim=0)                                                                                                                                                                                                                                                                                                                                                                                            
      687 def chunk_optional(tensor, chunks):                                                                                                                                                                                                                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
  RuntimeError: chunk expects `chunks` to be greater than 0, got: 0      
```